[project]
name = "pixelart"
version = "0.1.0"
description = "pixelart converter"
authors = [
    { name = "akazdayo", email = "82073147+akazdayo@users.noreply.github.com" },
]
dependencies = [
    "streamlit>=1.36.0",
    "opencv-python-headless>=4.10.0.84",
    "numpy>=2.0.0",
    "pillow>=10.4.0",
    "scikit-learn>=1.5.1",
    "watchdog>=4.0.1",
    "colorama>=0.4.6",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["opencv-python>=4.10.0.84"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pixelart"]
